### PR TITLE
Search page

### PR DESCRIPTION
**Pull request by Splatts7**
Fully functional, although looks pretty plain. Also need to fix some book cover dimensions, as some are much larger than others.

### CODE REVIEW

**Comment by Ka-Ma** [comment]
some books are much larger than others. If you want them all the same size we could set the image size in css

**Comment by Ka-Ma** [comment]
also I noticed that my recent books is reduced to 1 because "recent" is within the last 7 days.

**Comment by Splatts7** [comment]
Will have to go through the database and set some book's dates to the future then maybe? Or change the "recent" to the 3 MOST recently added, regardless of how long ago it was.

**Comment by Splatts7** [comment]
Same image size would be good too. Make the page look more professional.

**Comment by Ka-Ma** [comment]
I'll make those adjustments

**Pull request merged**
